### ISSUE TITLE
Question: Does this work on amazfit GTS or GTR?

### ISSUE THREAD

**Issue by felixsanz** [Klaus3d3/xDrip-Watchface#15]
^

**Comment by pavelvanecekcz** [comment]
There are different resolution on GTS/GTR. Stratos has 320x300.

**Comment by yosepito** [comment]
My guess is that it might work on GTR but not in GTS. The GTR has a rounded screen and it is likely the android behind it can be similar to Pace/Stratos. However, I've read that you cannot install apks in these watches (e.g. google maps...) while you can do it i Pace/Stratos. It's a similar problem with Bip: the OS does not allow additional installations. 
If you have one, you can test by simply following the instructions (installation of Huami Amazfit Tool and check whether you can install it or try via adb commands as said elsewhere in any of the issues opened here).

**Comment by pavelvanecekcz** [comment]
I'm afraid that GTS (and GTR) has its own proprietary system, not based on Android.

**Comment by felixsanz** [comment]
yeah, both has amazfit OS. So... What about Verge 2? is "modded android" or amazfit OS?

**Comment by GreatApo** [comment]
> yeah, both has amazfit OS. So... What about Verge 2? is "modded android" or amazfit OS?

Only Pace, Stratos, Verge and Stratos 3 have Android versions compatible (Nexo has Android 8 and it probably doesn't work). Now the current code can work on Pace and Stratos and can/could be ported to Verge and Stratos 3.

**Comment by felixsanz** [comment]
i'm probably going to buy one of those, since my pebble is dying. so i can help with coding and testing

but a question, how does this work in general? xdrip has an amazfit service, is pushing data to the watch or the watch pulls the data?

also, now my xdrip shows steps and heartrate taken from pebble, does it work with amazfit too?

thanks in advance

**Comment by GreatApo** [comment]
> i'm probably going to buy one of those, since my pebble is dying. so i can help with coding and testing

Pace is quite appealing and the cheapest. You can get a used one or buy a new under $80 (I got one 2 years ago at that price :P ). 

> but a question, how does this work in general? xdrip has an amazfit service, is pushing data to the watch or the watch pulls the data?

I think the phone sends the data, but can be done both ways.

> also, now my xdrip shows steps and heartrate taken from pebble, does it work with amazfit too?

I am not actually using XDrip thus I can't verify that, however, you could code that the same way (but probably it's not coded in XDrip).

**Comment by yosepito** [comment]
> 
> 
> i'm probably going to buy one of those, since my pebble is dying. so i can help with coding and testing
> 
> but a question, how does this work in general? xdrip has an amazfit service, is pushing data to the watch or the watch pulls the data?
> 
> also, now my xdrip shows steps and heartrate taken from pebble, does it work with amazfit too?
> 
> thanks in advance

Felix: puedes seguir los pasos indicados aquí a partir del 4 https://github.com/Klaus3d3/xDrip-Watchface/issues/4
You can follow steps from 4 in that link. However, as said, it will only work on those models of Amazfit because the smartwatch should have a certain operative system. You should install the watchface as commented there. You should download latest versions of Xdrip in smartwatch and you should also run the app Amazfit (the app of the smartwatch) always in the background once you active the option in Xdrip. Otherwise, Xdrip will crash. the App Amazfit is the bridge between Xdrip and smartwatch. There are some pics of the smartwatch in some of the earlier issues opened here. 
Yes, Xdrip will show steps and heart rate (data) and it will appear a green circle by the line of BG=100 that is proportional to the number of steps by that hour. 

I use it also for uploading my workouts in the bike to Strava, so Amazfit Pace is the best for me. My advice to everyone is to charge  the smartwatch with a USB to a computer and not to use a smartphone charger higher than let's say 500 mAh. Mine is 24 hrs connected and it lasted 1 day and 20 hours when charged with a plugin of 1000 mAh. Now I charge it with the plugin of the Freestyle reader -which is 500 mAh- and now it lasts nearly 3 days. Impressive how this affects battery duration.

In Aliexpress you may find a Pace by 60 euros, more or less. When I bought it a year and half ago, it costed 80 euros, approx. You may search in the usual websites for the cheapest (i.e., Gearbest, Aliexpress, Geekbuying...) Don't worry about language: you can change it in the smartwatch.

Wish you the best and in case you have troubles, you can contact me. Send me a private message in Spanish (soy español y te puedo ayudar si tienes dudas)
best wishes

**Comment by yosepito** [comment]
![Screenshot_2019-11-12-23-06-14-578_com eveningoutpost dexdrip](https://user-images.githubusercontent.com/40143924/68715134-9374cb80-05a1-11ea-9a25-dd1fbbe61d21.png)
Here you can see how it will show your data (#steps and heart rate). Yes, I was quiet so HR=63. Bike workout is doing its job ;)
Amazift app is the bridge sending/receiving data to/from smartwatch and Xdrip, this is why you need to keep it activated (and do exactly the same as you do with Xdrip to maintain it in the background, avoiding the android cleaning the cache....)

**Comment by felixsanz** [comment]
gracias @yosepito! very useful :)

so... how xdrip gets/send data from amazfit app? there is an api or some sort of developer server?

Related to #4, the graph is generated on the phone as a picture and then pushed to the watch as a background image (same as if you have a cat picture) right? whats the update rate, every 5 minutes?

doesn't all this stuff consume too much battery on the watch?

**Comment by yosepito** [comment]
Please, find my answers below:

_> so... how xdrip gets/send data from amazfit app? there is an api or some sort of developer server?_
**Really I don't know and don't mind. What I know is that you only have to install Xdrip and Amazift app. That's all. The code in Xdrip is responsible for connecting both Xdrip & smartwatch through Amazfit (since the smartwatch is connected by BT and you can see the info in the smartphone, so that is the link....). Anyway, do you really need to know how it works? In that case, perhaps the developers can tell or simply read the code. I'm unable to understand it fully**
_> Related to #4, the graph is generated on the phone as a picture and then pushed to the watch as a background image (same as if you have a cat picture) right? whats the update rate, every 5 minutes?_
**Not that way. It is like many others watchfaces: it collects data already present in the smartwatch (time, steps counting, date...) and the developer has added the data sent by Xdrip. If you are not familiar with how to build your own watchface, you can google it. It seems it is easier to develop watchfaces for round smartwatches than for squared ones, but the main issue is the running operative system; you may find Wear OS android-based SOs...** 
You can see examples here https://github.com/Klaus3d3/xDrip-Watchface/issues/11
You can only set the language, but the info you will see is that. You can hide the small dots of the graph or depict tiny dots instead, but you cannot change the "fields" that are shown. For instance, we don't have HR here. But, is it relevant? You can see battery of both watch and smartphone....trend arrow, delta and BG from Xdrip

_> doesn't all this stuff consume too much battery on the watch?>_
**As said, the idea to me is to have this linked to smartphone permanently. If you want, you can put the smartwatch in plan mode so it will disconnect from smartphone. Neither did you receive alerts nor BGs. Alerts is a very nice feature since the smartwatch vibrates so my best half can sleep at nights if Xdrip alerts about going low. A kind of silent alert, which I appreciate much even when working. In my case, it lasts nearly 3 days, more or less the same as the smartphone (a Redmi 3s with 4100 mAh of battery that lasted 5-6 days when I didn't use Xdrip). Now, both last about 2 and half day, which is enough to me.
Hope this info helps you make a decision**

**Comment by GreatApo** [comment]
I think it goes like this: the connection is handled by the Amazfit app, XDrip sends the data and finally the watchface has a receiver that listens for these data.
There is no documentation since all of these come from hacking the existing libraries.

The transferred picture code can be improved by creating the picture within the watch. I don't remember if the current code is like that or not.

There is a battery consumption coming from all these, however the connection is generally efficient compared to other Bluetooth connections not established through Amazfit app.

**Comment by felixsanz** [comment]
For future users:

https://github.com/NightscoutFoundation/xDrip/blob/80e1023b295b27c1f55bc48ef5212faaf859aefb/app/src/main/java/com/eveningoutpost/dexdrip/wearintegration/Amazfitservice.java

**Comment by twinko** [comment]
guys, is there any progress on this project? would like to buy the GTR but if i cant use xdrip+ its a dealbreaker for me :(

**Comment by GreatApo** [comment]
@twinko This can work only on android based systems. GTR is not android based (it won't work). I would suggest buying a Stratos or a Pace.

**Comment by twinko** [comment]
@GreatApo thank you for your fast reply! Does it matter which version? There is a stratos 3 now.

**Comment by GreatApo** [comment]
@twinko I didn't mention Stratos 3 and Verge on purpose. Stratos 3 has a BLE connection which works but the way the current project utilizes the connection will make data transfer extremely slow. I can't say for sure if it will properly work or not.
Additionally, Stratos 3 has a bigger screen and different watch libs. If you are a dev you can work this problem out but I wouldn't suggest that for others. Verge has the same problem.

Btw, Stratos and Stratos 2 is the same watch.
